#ifndef VIRTUALMEMFRAMEWORKC_MULTITHREADEDHEAPTESTS_H
#define VIRTUALMEMFRAMEWORKC_MULTITHREADEDHEAPTESTS_H

void testMultiThreadedWriteHeapAndReadFullPage();
void testMultiThreadedWriteHeapAndReadAcrossTwoPages();
void testMultiThreadedWriteHeapAndReadMiddleOfPage();
void testMultiThreadedWriteHeapAndReadPartial();
void testMultiThreadedReadAllHeapMemory();
#endif